name: BUILD WIN
on: [push]
jobs:
  build-windows-default:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master    
    - name: config site
      run:
        echo "" >> pjlib/include/pj/config_site.h        
    - name: test ossl
      run:
        dir "C:\Program Files\OpenSSL"
