name: BUILD WIN
on: [push]
jobs:
  build-windows-default:
    runs-on: windows-latest
    steps:
    - uses: ilammy/setup-nasm@v1 
    - name: get openssl
      run: git clone --single-branch --branch OpenSSL_1_1_1-stable https://github.com/openssl/openssl.git
    - name: configure openssl
      run: cd openssl; perl Configure VC-WIN32 --prefix=c:\openssl-build
