name: BUILD WIN
on: [push]
jobs:
  build-mac-default-full-bundle-1:
  # full bundle: enable all codecs + AEC + DTLS
  # full bundle 1: running pjlib, pjlib-util, pjmedia, and pjsua tests
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: brew install opencore-amr swig sipp
    - name: config site
      run: cd pjlib/include/pj && cp config_site_test.h config_site.h
    - name: configure
      run: CFLAGS="-g -I/usr/local/include -I/usr/local/opt/openssl/include -fPIC" LDFLAGS="-L/usr/local/lib -L/usr/local/opt/openssl/lib" CXXFLAGS="-g -fPIC" ./configure
    - name: make
      run: make
    - name: swig bindings
      run: cd pjsip-apps/src/swig && make
    - name: disable firewall
      run: sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off
    - name: unit tests
      run: make pjsua-test