name: BUILD WIN
on: [push]
jobs:
  build-windows-default:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: get openssl
      run: Invoke-WebRequest -Uri "https://mirror.firedaemon.com/OpenSSL/openssl-1.1.1e-dev.zip" -OutFile ".\openssl.zip"
      shell: powershell
    - name: expand openssl
      run: Expand-Archive -LiteralPath .\openssl.zip -DestinationPath .\openssl_build\; pwd
      shell: powershell
    - name: check openssl folder
      run: |
        dir "D:\a\pjproject\pjproject\openssl_build\openssl-1.1\x86\include"
        dir "D:\a\pjproject\pjproject\openssl_build\openssl-1.1\x86\lib"
      shell: powershell    
    - name: config site
      run:
        cd pjlib/include/pj; cp config_site_test.h config_site.h; Add-Content config_site.h "#define PJ_HAS_SSL_SOCK 1"
      shell: powershell
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
      with:
        vs-version: 14.0
    - name: check VsDevCmd.bat
      run: dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
      shell: cmd
    - name: MSBuild
      working-directory: .
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
        dir D:\a\pjproject\pjproject\openssl_build\openssl-1.1\x86\include
        dir D:\a\pjproject\pjproject\openssl_build\openssl-1.1\x86\lib
        set INCLUDE=%INCLUDE%;D:\a\pjproject\pjproject\openssl_build\openssl-1.1\x86\include
        set LIB=%LIB%;D:\a\pjproject\pjproject\openssl_build\openssl-1.1\x86\lib
        echo on
        echo "=======INCLUDE FOLDER====="
        echo %INCLUDE%
        echo "=======LIB FOLDER====="
        echo %LIB%
        msbuild pjproject-vs14.sln /p:PlatformToolset=v142 /p:Configuration=Debug /p:Platform=win32 /p:UseEnv=true
      shell: cmd
