name: BUILD WIN
on: [push]
jobs:
  build-windows-default:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master    
    - name: config site
      run:
        echo "" >> pjlib/include/pj/config_site.h        
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
      with:
        vs-version: 14.0
    - name: MSBuild
      working-directory: .
      run: msbuild pjproject-vs14.sln /p:PlatformToolset=v142 /p:Configuration=Debug /p:Platform=win32
    - name: unit tests
      run: pjlib/bin/pjlib-test-i386-Win32-vc14-Debug.exe;pjlib-util/bin/pjlib-util-test-i386-Win32-vc14-Debug.exe;pjmedia/bin/pjmedia-test-i386-Win32-vc14-Debug.exe
