name: BUILD WIN
on: [push]
jobs:
  build-windows-default:
    runs-on: windows-latest
    steps:
    - name: get openssl
      run: Invoke-WebRequest -Uri "https://mirror.firedaemon.com/OpenSSL/openssl-1.1.1e-dev.zip" -OutFile ".\openssl.zip"
    - name: expand openssl
      run: Expand-Archive -LiteralPath .\openssl.zip -DestinationPath .\openssl_build\
    - name: test zip
      run: dir .\openssl_build
    - uses: actions/checkout@master    
    - name: config site
      run:
        cd pjlib/include/pj; cp config_site_test.h config_site.h; Add-Content config_site.h "#define PJ_HAS_SSL_SOCK 1"
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
      with:
        vs-version: 14.0
    - name: set environment var
      run: $env:INCLUDE += ";.\openssl_build\openssl-1.1\x86\include";$env:LIB += ";.\openssl_build\openssl-1.1\x86\lib"
    - name: print INCLUDE
      run: $env:INCLUDE
    - name: print LIB
      run: $env:LIB
    - name: MSBuild
      working-directory: .
      run: msbuild pjproject-vs14.sln /p:PlatformToolset=v142 /p:Configuration=Debug /p:Platform=win32 /p:UseEnv=true
